### ISSUE TITLE
Quitting?

### ISSUE THREAD

**Issue by alexschrod** [jice-nospam/doryen-rs#14]
I may have missed something obvious, but... how do I signal to the `App` that I'm done? Like, from a "Quit" menu option in the game, or deliberately ending the game when the player has reached the end?

Also, in sort of the opposite vein, it'd be nice to informed when the player attempts to close the game (by e.g. clicking the X on the window), since it can be nice to be like "Whoa there, you sure you want to quit without saving first? You haven't saved in 53 minutes." (or for an even better UX, use that opportunity to run the auto-save routine)

**Comment by jice-nospam** [comment]
This is not yet supported by the underlying uni_app framework. The framework below uni_app (winit) has support for CloseRequested events but it doesn't seem to be implemented on the web platform. In the short term, this could be made available for doryen-rs projects only on the native side. I'll have a look at that asap.

**Comment by jice-nospam** [comment]
this works know on master. Please check the exit example
