### ISSUE TITLE
Don't use wildcard dependencies when relying on features from very specific versions

### ISSUE THREAD

**Issue by alexschrod** [jice-nospam/doryen-rs#15]
After you added the feature in #14 I went to update `doryen-rs`. This led to a compilation error:
```
error[E0560]: struct `uni_app::AppConfig` has no field named `intercept_close_request`
   --> C:\Users\alexs\.cargo\registry\src\github.com-1ecc6299db9ec823\doryen-rs-1.2.0\src\app.rs:177:13
    |
177 |             intercept_close_request: options.intercept_close_request,
    |             ^^^^^^^^^^^^^^^^^^^^^^^ `uni_app::AppConfig` does not have this field
    |
    = note: available fields are: `title`, `size`, `vsync`, `headless`, `fullscreen` ... and 2 others

error[E0599]: no variant or associated item named `CloseRequested` found for type `uni_app::AppEvent` in the current scope
   --> C:\Users\alexs\.cargo\registry\src\github.com-1ecc6299db9ec823\doryen-rs-1.2.0\src\input.rs:120:23
    |
120 |             AppEvent::CloseRequested => {
    |                       ^^^^^^^^^^^^^^ variant or associated item not found in `uni_app::AppEvent`

error: aborting due to 2 previous errors
```
Since `doryen-rs`'s dependency on `uni-app` is set to `version="0.1.*"`, the version I already had installed from before, i.e. `0.1.0`, satisfied it. But `0.1.0`'s `App` doesn't have `intercept_close_request`, and its `AppEvent` doesn't have a `CloseRequested` variant!

Only after manually updating `uni-app` from `0.1.0` to `0.1.1` did `doryen-rs` compile successfully again.

**Comment by jice-nospam** [comment]
I made a mistake by publishing a 0.1.1 uni-app that breaks compatibility with 0.1.0. It should have been 0.2.0 but unrust documentation states everywhere that 0.2.0 will be the stable version so I'm a bit stuck. I'll reach unrust's main maintainer to see how we handle that.

For doryen-rs, this is fixed by upgrading to 1.2.0 version.
