### ISSUE TITLE
transparency not working properly?

### ISSUE THREAD

**Issue by imoea** [jice-nospam/doryen-rs#18]
In the following test example, the printed rectangle should remain almost invisible with an alpha value of 1 out of 255. It however gets more opaque over time up to a certain point. Is this the intended behaviour or a rendering issue?

```rust
extern crate doryen_rs;

use doryen_rs::{App, AppOptions, DoryenApi, Engine, UpdateEvent};

struct MyRoguelike;

impl Engine for MyRoguelike {
    fn init(&mut self, _api: &mut dyn DoryenApi) {}
    fn update(&mut self, _api: &mut dyn DoryenApi) -> Option<UpdateEvent> {
        None
    }
    fn render(&mut self, api: &mut dyn DoryenApi) {
        let con = api.con();
        con.clear(None, None, None);
        con.rectangle(
            20,
            10,
            40,
            25,
            Some((255, 255, 255, 1)),
            Some((255, 255, 255, 1)),
            Some(' ' as u16),
        );
    }
    fn resize(&mut self, _api: &mut dyn DoryenApi) {}
}

fn main() {
    let mut app = App::new(AppOptions {
        window_title: "alpha test".to_owned(),
        ..Default::default()
    });
    app.set_engine(Box::new(MyRoguelike));
    app.run();
}
```

**Comment by jice-nospam** [comment]
`con.clear(None, None, None)`

You're not clearing anything here. Thus you keep rendering the rectangle on top of itself. Set a black background color to actually clear the console.

**Comment by imoea** [comment]
I've actually tried a few variants, with and without `fore`, `back` and `fillchar`, including the following
```rust
con.clear(Some((0, 0, 0, 255)), None, Some(' ' as u16));
```
as taken from your `blit.rs` example, and
```rust
con.clear(Some((0, 0, 0, 255)), Some((0, 0, 0, 255)), Some(' ' as u16));
```

**Comment by jice-nospam** [comment]
Indeed, there's something fishy here... 
I'll check this asap

**Comment by jice-nospam** [comment]
Ok what's happening is that the Console.clear only clear the console, not the opengl viewport, so you constantly blit a semi transparent console on it and it adds over time.

Semi transparent colors should not be used with the root console (DoryenApi.con()) except if you want to achieve such effect where each frame is displayed on top of the previous one. Instead you should only use only opaque colors (alpha=255) on the root console, and transparent colors on offscreen consoles that you blit on the root console.

I could clear the openGL buffer each frame, but that would make overlaying frames on top of each other impossible while the current system allows both behaviour.

So for your example to work, simply replace the color (255,255,255,1) by (1,1,1,255) which is the result when the transparent color (255,255,255,1) is blitted on top of black (0,0,0,255). You don't even need to clear the console as the rectangle is rendered every frame :
```
    fn render(&mut self, api: &mut dyn DoryenApi) {
        let con = api.con();
        con.rectangle(
            20,
            10,
            40,
            25,
            Some((1, 1, 1, 255)),
            Some((1, 1, 1, 255)),
            Some(' ' as u16),
        );
    }
```
Note that the color 1,1,1 is barely distinguishable from 0,0,0. Also drawing a rectangle with the same foreground and background color doesn't make sense as you won't see the rectangle frame as it has the same color as the background.

**Comment by jice-nospam** [comment]
I've just noticed that the behaviour is different on native and web platforms. The web platform actually clear the gl framebuffer every frame. I'll see if I can fix that.

**Comment by jice-nospam** [comment]
Ok issue fixed in uni-gl : https://github.com/unrust/uni-gl/issues/7

I added an "alpha" example in doryen-rs to showcase framebuffer overdrawing

**Comment by imoea** [comment]
So how should I go about making something like glyphs/text fading in and out on an arbitrary background colour? One way is to recompute the RGB values so they approach a target colour where they blend in while keeping alpha at 255. Alternatively, it could be as simple as toggling the alpha value. Which is the recommended way of implementing this?

**Comment by jice-nospam** [comment]
draw them on another console and then blit it on the root console as in the blit example.

**Comment by imoea** [comment]
I was guessing that was the only way. I was experimenting on another way of doing it instead of creating a new console for each glyph that has a different alpha but i guess not. I think I have an idea of how to do this using multiple consoles now. Thanks!

**Comment by jice-nospam** [comment]
you can also use a single offscreen console the same size as the root console and draw everything on it using a different alpha channel in the color of each glyph. Then you blit the console with fore_alpha = back_alpha = 1.0

**Comment by jice-nospam** [comment]
mmh it seems console blitting doesn't take the color alpha channel into account but that's something that can be fixed. Having to create a console for each different alpha value is dumb

**Comment by imoea** [comment]
Do the alpha channels have to be the same on the same offscreen console or can they be different? Because the latter doesn't work. Unless that's not the way it's supposed to work. I'm still trying to understand how this works.

**Comment by jice-nospam** [comment]
Ok I've just push something that might help you. You can check the updated blit example, one of the console has varying alpha values and they're taken into account when it's blitted on the root console.

**Comment by imoea** [comment]
The alpha blending only seems to be working for `back` and not `fore`. Is this the intended behaviour?
```rust
con.clear(None, Some((0, 0, 0, 255)), Some(' ' as u16));
let mut c1 = Console::new(80, 45);
c1.ascii(40, 25, 0xe6);  // ▚ glyph
c1.fore(40, 25, (255, 255, 255, 64));  // alpha stays at 255
c1.back(40, 25, (255, 255, 255, 64));  // alpha works as intended
c1.blit(0, 0, con, 1.0, 1.0, None);
```

**Comment by jice-nospam** [comment]
Yes. This is still an ASCII console and you can't draw overlapping characters in one cell.

**Comment by imoea** [comment]
Understood. Thanks!
