### ISSUE TITLE
Displaying a formatted text

### ISSUE THREAD

**Issue by skyne98** [jice-nospam/doryen-rs#2]
Hey there! Another issue for ya! Printing colored strings via %{color} is very convenient, but it doesn't allow you to have something like ```format!("%{white}Move with %{red}arrows %{} {}", fps)```.

**Comment by jice-nospam** [comment]
mmh indeed. I made a poor choice of color markers... This is something that can be fixed quickly. What markers would be best?

**Comment by skyne98** [comment]
@jice-nospam, to be honest, I am thinking about something like #[color]. It looks like rust own attribute syntax and is slightly easier to type.
