### ISSUE TITLE
Resize issue about mouse position

### ISSUE THREAD

**Issue by buxx** [jice-nospam/doryen-rs#22]
I'm testing resizing example script. I have trouble about mouse position, to see the problem, apply following diff on `examples/resize.rs`:

``` diff
diff --git a/examples/resize.rs b/examples/resize.rs
index 2fcc172..b008fb3 100644
--- a/examples/resize.rs
+++ b/examples/resize.rs
@@ -5,13 +5,18 @@ use doryen_rs::{App, AppOptions, DoryenApi, Engine, TextAlign};
 struct MyRoguelike {
     width: u32,
     height: u32,
+    mouse_pos: (f32, f32),
 }
 
 impl Engine for MyRoguelike {
     fn init(&mut self, _api: &mut dyn DoryenApi) {}
-    fn update(&mut self, _api: &mut dyn DoryenApi) {}
+    fn update(&mut self, api: &mut dyn DoryenApi) {
+        let input = api.input();
+        self.mouse_pos = input.mouse_pos();
+    }
     fn render(&mut self, api: &mut dyn DoryenApi) {
         let con = api.con();
+        con.clear(Some((0, 0, 0, 255)), Some((0, 0, 0, 255)), Some(' ' as u16));
         con.rectangle(
             0,
             0,
@@ -38,6 +43,7 @@ impl Engine for MyRoguelike {
             None,
             None,
         );
+        con.back(self.mouse_pos.0 as i32, self.mouse_pos.1 as i32, (255, 255, 255, 255))
     }
     fn resize(&mut self, api: &mut dyn DoryenApi) {
         self.width = api.get_screen_size().0 / 8;
@@ -51,6 +57,7 @@ impl MyRoguelike {
         Self {
             width: 80,
             height: 50,
+            mouse_pos: (0.0, 0.0)
         }
     }
 }
```

Then run it. After resize the window, mouse position don't match with console coordinate. Is that a problem what i have to manage in `MyRoguelike.resize` function ? It should not been automatically managed in `con().resize` function ?

**Comment by jice-nospam** [comment]
It's a bug. Thanks for the report, I'm checking it asap

**Comment by jice-nospam** [comment]
It should work now on master branch. There was another issue with resizing consoles : when using a hidpi screen, the hidpi factor was not taken into account (you would get a bigger console with smaller characters than expected).

Also your resize example is not up to date. Expect some API changes when you upgrade to the latest master version (see version 1.2.1 changelog).

**Comment by buxx** [comment]
👍
