### ISSUE TITLE
no max_fps?

### ISSUE THREAD

**Issue by shingle-bells** [jice-nospam/doryen-rs#29]
I keep getting an error when using the examples.
`error[E0560]: struct 'doryen_rs::AppOptions' has no field named 'max_fps'`
Specifically, I copied from the `lowfps.rs` example, and modified nothing. What am I missing?

**Comment by jice-nospam** [comment]
I guess you're not using the doryen-rs version from master branch. The max_fps feature is not yet on crates.io (cf CHANGELOG.md).
Just set your dependency to
`doryen-rs= { git="https://github.com/jice-nospam/doryen-rs" }`
