### ISSUE TITLE
Constants for symbol characters

### ISSUE THREAD

**Issue by AlexMooney** [jice-nospam/doryen-rs#7]
I'd like to be able to have a constant like `ARROW_N` instead of having to define my own constants to print those characters.  How about we include [this file](https://github.com/tomassedovic/tcod-rs/blob/master/src/chars.rs) in this library?

<details> <summary>The characters with doyren-rs typecasting</summary>

```rust
pub const HLINE: u16 = '\u{c4}' as u16;
pub const VLINE: u16 = '\u{b3}' as u16;
pub const NE: u16 = '\u{bf}' as u16;
pub const NW: u16 = '\u{da}' as u16;
pub const SE: u16 = '\u{d9}' as u16;
pub const SW: u16 = '\u{c0}' as u16;
pub const TEEW: u16 = '\u{b4}' as u16;
pub const TEEE: u16 = '\u{c3}' as u16;
pub const TEEN: u16 = '\u{c1}' as u16;
pub const TEES: u16 = '\u{c2}' as u16;
pub const CROSS: u16 = '\u{c5}' as u16;
pub const DHLINE: u16 = '\u{cd}' as u16;
pub const DVLINE: u16 = '\u{ba}' as u16;
pub const DNE: u16 = '\u{bb}' as u16;
pub const DNW: u16 = '\u{c9}' as u16;
pub const DSE: u16 = '\u{bc}' as u16;
pub const DSW: u16 = '\u{c8}' as u16;
pub const DTEEW: u16 = '\u{b9}' as u16;
pub const DTEEE: u16 = '\u{cc}' as u16;
pub const DTEEN: u16 = '\u{ca}' as u16;
pub const DTEES: u16 = '\u{cb}' as u16;
pub const DCROSS: u16 = '\u{ce}' as u16;
pub const BLOCK1: u16 = '\u{b0}' as u16;
pub const BLOCK2: u16 = '\u{b1}' as u16;
pub const BLOCK3: u16 = '\u{b2}' as u16;
pub const ARROW_N: u16 = '\u{18}' as u16;
pub const ARROW_S: u16 = '\u{19}' as u16;
pub const ARROW_E: u16 = '\u{1a}' as u16;
pub const ARROW_W: u16 = '\u{1b}' as u16;
pub const ARROW2_N: u16 = '\u{1e}' as u16;
pub const ARROW2_S: u16 = '\u{1f}' as u16;
pub const ARROW2_E: u16 = '\u{10}' as u16;
pub const ARROW2_W: u16 = '\u{11}' as u16;
pub const DARROW_H: u16 = '\u{1d}' as u16;
pub const DARROW_V: u16 = '\u{12}' as u16;
pub const CHECKBOX_UNSET: u16 = '\u{e0}' as u16;
pub const CHECKBOX_SET: u16 = '\u{e1}' as u16;
pub const RADIO_UNSET: u16 = '\u{09}' as u16;
pub const RADIO_SET: u16 = '\u{0a}' as u16;
pub const SUBP_NW: u16 = '\u{e2}' as u16;
pub const SUBP_NE: u16 = '\u{e3}' as u16;
pub const SUBP_N: u16 = '\u{e4}' as u16;
pub const SUBP_SE: u16 = '\u{e5}' as u16;
pub const SUBP_DIAG: u16 = '\u{e6}' as u16;
pub const SUBP_E: u16 = '\u{e7}' as u16;
pub const SUBP_SW: u16 = '\u{e8}' as u16;
pub const SMILIE: u16 = '\u{01}' as u16;
pub const SMILIE_INV: u16 = '\u{02}' as u16;
pub const HEART: u16 = '\u{03}' as u16;
pub const DIAMOND: u16 = '\u{04}' as u16;
pub const CLUB: u16 = '\u{05}' as u16;
pub const SPADE: u16 = '\u{06}' as u16;
pub const BULLET: u16 = '\u{07}' as u16;
pub const BULLET_INV: u16 = '\u{08}' as u16;
pub const MALE: u16 = '\u{0b}' as u16;
pub const FEMALE: u16 = '\u{0c}' as u16;
pub const NOTE: u16 = '\u{0d}' as u16;
pub const NOTE_DOUBLE: u16 = '\u{0e}' as u16;
pub const LIGHT: u16 = '\u{0f}' as u16;
pub const EXCLAM_DOUBLE: u16 = '\u{13}' as u16;
pub const PILCROW: u16 = '\u{14}' as u16;
pub const SECTION: u16 = '\u{15}' as u16;
pub const POUND: u16 = '\u{9c}' as u16;
pub const MULTIPLICATION: u16 = '\u{9e}' as u16;
pub const FUNCTION: u16 = '\u{9f}' as u16;
pub const RESERVED: u16 = '\u{a9}' as u16;
pub const HALF: u16 = '\u{ab}' as u16;
pub const ONE_QUARTER: u16 = '\u{ac}' as u16;
pub const COPYRIGHT: u16 = '\u{b8}' as u16;
pub const CENT: u16 = '\u{bd}' as u16;
pub const YEN: u16 = '\u{be}' as u16;
pub const CURRENCY: u16 = '\u{cf}' as u16;
pub const THREE_QUARTERS: u16 = '\u{f3}' as u16;
pub const DIVISION: u16 = '\u{f6}' as u16;
pub const GRADE: u16 = '\u{f8}' as u16;
pub const UMLAUT: u16 = '\u{f9}' as u16;
pub const POW1: u16 = '\u{fb}' as u16;
pub const POW3: u16 = '\u{fc}' as u16;
pub const POW2: u16 = '\u{fd}' as u16;
pub const BULLET_SQUARE: u16 = '\u{fe}' as u16;
```

</details>

**Comment by jice-nospam** [comment]
libtcod had such constants. The problem is that most of those characters are not standard and nothing forces a font to have them at those positions. So most of the time, they don't work. I'd rather have a function like
```fn get_code_for_char(ch: CharEnum) -> Option<u16>``` 
and then each font should be able to provide data for this function to work.

**Comment by AlexMooney** [comment]
Yeah I see what you mean.  So then a font would have to have more information than just the png file.

Do you think it would make sense to define a `CharEnum` set with the symbols listed, and then make a `HashMap<CharEnum, u16>` to implement `get_code_for_char` for default font layouts?  Then folks could override the hash if they have a font with characters moved around.

Maybe this is too much work, and they can just define the constants they're using, as I did in my project.

**Comment by jice-nospam** [comment]
In fact, we can't even have a `CharEnum` because the list of values depends on the font.
So that would be `get_code_for_char(char_name: &str)` which is slow and this would force the user to define his custom chars nonetheless with some `set_code_for_char(char_name: &str, code: u16)`. In the end, that's not an improvement over having the user simply defining his u16 constants.

So indeed I think we'd better keep it as it is right now, don't you think ?

**Comment by AlexMooney** [comment]
Hm, you're probably right that the general case is intractable.

Still, I expect most folks would be using a standard-ish font layout.  After all, we're not forcing them to map the alpha-numeric symbols on their own.  Is there a happy middle ground that will help people in the typical use cases without getting in the way of people who are running a customized font with a `TREASURE_CHEST` symbol?  I don't believe having those constants around would be a problem; they can simply not import the ones that aren't correct for their font, right?

**Comment by jice-nospam** [comment]
I could at least make public the special characters that are used internally by the library (hence they are kind of mandatory in the font). They're in console.rs :
```
// rectangle drawing kit
pub const CHAR_CORNER_NW: u16 = 218;
pub const CHAR_CORNER_SW: u16 = 192;
pub const CHAR_CORNER_SE: u16 = 217;
pub const CHAR_CORNER_NE: u16 = 191;
pub const CHAR_LINE_H: u16 = 196;
pub const CHAR_LINE_V: u16 = 179;
// sub-pixel resolution kit
pub const CHAR_SUBP_NW: u16 = 226;
pub const CHAR_SUBP_NE: u16 = 227;
pub const CHAR_SUBP_N: u16 = 228;
pub const CHAR_SUBP_SE: u16 = 229;
pub const CHAR_SUBP_DIAG: u16 = 230;
pub const CHAR_SUBP_E: u16 = 231;
pub const CHAR_SUBP_SW: u16 = 232;
```
For the other characters, I'm afraid it's too specific. But I'll update the documentation to provide a link to your chars.rs file so that people can easily copy it in their project.
