### ISSUE TITLE
Black Edge in Examples

### ISSUE THREAD

**Issue by nsmryan** [jice-nospam/doryen-rs#8]
When I view the examples, there is a black edge on the top and right side. This doesn't seem right, but I can't figure out what about the code, or the index.html, would cause this.

![Capture](https://user-images.githubusercontent.com/1892046/55526554-96026080-5663-11e9-9ba9-cae84e493690.PNG)

**Comment by jice-nospam** [comment]
What browser/version are you using ?

**Comment by nsmryan** [comment]
Sorry about that, didn't think to mention my setup. Here is what I see:

Black edge on top and right:
Android phone with Firefox 66.0.2
Android phone with Chrome 73.0.3683.90.
Windows Laptop with Firefox 60.6.1esr
Windows Laptop with Chrome 73.0.3683.86

Looks good, no black edge:
Ubuntu laptop in Firefox 66.0.

Doesn't load at all:
Windows laptop, Internet Explorer 11.1689.15063.0

**Comment by jice-nospam** [comment]
Ok, internet explorer and edge are not supported.
I don't reproduce with firefox 66 (windows) and chromium 69 (windows).
I need to dig this more

**Comment by Zireael07** [comment]
The live walking @ example doesn't seem to load here either. Console says wasm wasn't loaded.

Ubuntu 18.04 LTS, Chrome 73

**Comment by jice-nospam** [comment]
Can you display the content of the javascript console ? The black border issue might be cause by cheesy OpenGL support, I've had that with a laptop using a non-gaming video card resulting in last-century OpenGL version... ;)

**Comment by Zireael07** [comment]
Error loading Rust wasm module 'basic': TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
roguecentral.org/:1 Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

The problem is only with the first example (live @ ) all the others seem to work.

**Comment by jice-nospam** [comment]
ok reproducing from newly compiled example. I'll check this asap

**Comment by jice-nospam** [comment]
Issue is linked to window.devicePixelRatio value. I have a double screen setup with different values for each screen (a HiDpi screen with 1.5 devicePixelRatio and a standard screen with 1.0 devicePixelRatio). The black bands appear only on the HiDpi screen.

**Comment by jice-nospam** [comment]
> The live walking @ example doesn't seem to load here either. Console says wasm wasn't loaded.

@Zireael07 The basic example is back online. Strangely enough, it was due to apache not serving the wasm file with the right mime-type. No idea was it still worked with other examples...
