### ISSUE TITLE
No characters on mobile

### ISSUE THREAD

**Issue by Zireael07** [jice-nospam/doryen-rs#9]
On my mobile phone, I can see the bg/fg colors, but not the characters. Chrome claims to support both webgl 1 and 2.
The gfx card is a Mali 720.

Checked both performance and Unicode demos, with the same results.

**Comment by jice-nospam** [comment]
Might be due to an issue while loading the font image. Can you get any information, like a javascript console or network requests status ? Not sure this is available on a mobile phone. Note that the library does not support touch event so it might not yet be useful for mobiles.

**Comment by jice-nospam** [comment]
closing this until more info provided
